config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index' # this is our homepage
    get 'signup', to: 'users#new' # get request to localhost:3000/users/new to sign up
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#destroy'

  resources :posts 
  resources :users, except: [:new]

  #resources :users, except: [:login]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
 belongs_to :user
 validates :user_id, presence: true
 validates :caption, presence: true, length: { minimum: 3, maximum: 40 }
 validates :comments, presence: true, length: { minimum: 3, maximum: 500 }
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :posts
 has_secure_password
 validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5, maximum: 20 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: { maximum: 40 }, uniqueness: { case_sensitive: false }, 
 format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  # By default, application controller methods are not available 
  # views, so they need to be defined as helper methods” so that the views can use them

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
     flash[:danger] = "You must be logged in to perform that action"
     redirect_to root_path
    end
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :post_helper, only: [:edit, :update, :show, :destroy]

  def new # action 
    @post = Post.new
  end

  def create # crud method - create a new post
    @post = Post.new(post_params)
    @post.user = User.first
    if @post.save
      flash[:notice] = "Post was successfully made"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit # action
  end

  def update  # crud method
    if @post.update(post_params)
     flash[:notice] = "Post was updated"
     redirect_to post_path(@post)
    else
     flash[:notice] = "Post was not updated"
     render 'edit'
    end
  end

  def index # action
    #@posts = Post.paginate(page: params[:page], per_page: 10)
    @posts = Post.all
  end 

  def destroy
    @post.destroy
    flash[:notice] = "Post was deleted"
    redirect_to posts_path
   end

  private
    
  def post_params # posts must have caption and comments field
    params.require(:post).permit(:caption, :comments)
  end

  def post_helper
    @post = Post.find(params[:id])
 end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create 
    user = User.find_by(email: params[:session][:email])
    if user  && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     flash[:success] = "You have logged in"
     redirect_to users_path(user)
    else
     flash.now[:danger] = "There was something wrong with your login information"
     render 'new'
    end
   end
 
   def destroy
    session[:user_id] = nil
    redirect_to root_path, alert: "You have logged out"
   end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     flash[:success] = "Welcome to Agilegram #{@user.username}"
     redirect_to posts_path
    else
     render 'new'
    end
   end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:success] = "Your account was updated successfully"
     redirect_to posts_path
    else
     render 'edit'
    end
   end

  

   def show
    @user = User.find(params[:id])
   end

   def index
   end

   private

   def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :email, :password)
   end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   size = options[:size]
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
   image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
 end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Agilegram", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agilegram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= render 'layouts/navigation' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1 align="center">Agilegram</h1>
<br>
<br>


<h5 align="center">Click to sign up for an Agilegram account</h5>
<br>
<br>
<div align="center">
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Login', login_path %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post do |f| %>
 <p>
  <%= f.text_field :caption %>
 </p>
 <p>
  <%= f.label :Comments %><br>
  <%= f.text_area :comments %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/posts/index.html.erb
<h1 align="center">All posts</h1>
<br>
<br>
<div id="createpost" align="center">
<li><%= link_to "Create Post", new_post_path %></li>
</div>
<br>
<br>
<br>

<%= render 'shared/post', obj: @posts %>
<br>
 <%= link_to 'Back', root_path %>

 <%= link_to 'Logout', logout_path %>

 <div align="center">

 
</div>

app/views/posts/new.html.erb
<h1 align="center">Make a post</h1>
<br>
<br>
<div align="center">
<%= form_for @post do |f| %>
 <p>
  <%= f.text_field :caption %>
 </p>
 <p>
  <%= f.label :comments %><br>
  <%= f.text_area :comments %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>
</div>

app/views/posts/show.html.erb
<h3 align="center">Showing selected post</h3>
<div align="center" id="post">
<p>
  <%= @post.caption %>
</p>
<p>
 Comments: <br>
 <%= @post.comments %>
</p>
</div>

<div align="center" id="links">
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to 'Back', posts_path %>
</div>

app/views/shared/_post.html.erb
<% obj.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="post-caption">
          <%= link_to post.caption, post_path(post) %>
        </div>
        <div class="post-body">
          <%= truncate(post.comments, length: 100) %>
          <div class="post-meta-details">
          <small>Created by: <%= post.user.username if post.user %>,
                    <%= time_ago_in_words(post.created_at) %> ago,
                    last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
        </div>
        <div class="post-actions">
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">All Users</h1>
<div align="center">
 
 <% @users.each do |user| %>
  <ul class="listing">
   <div class="row">
    <div class="well col-md-4 col-md-offset-4">
     <li><%= link_to gravatar_for(user), user_path(user) %></li>
     <li class="post-title"><%= link_to user.username, user_path(user) %></li>
     <li><small><%= pluralize(user.post.count, "article") if user.posts %></small></li>
    </div>
   </div>
  </ul>
 <% end %>

</div>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">
 
 <% @users.each do |user| %>
  <ul class="listing">
   <div class="row">
    <div class="well col-md-4 col-md-offset-4">
     <li><%= link_to gravatar_for(user), user_path(user) %></li>
     <li class="post-caption"><%= link_to user.username, user_path(user) %></li>
     <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
    </div>
   </div>
  </ul>
 <% end %>

</div>

app/views/users/new.html.erb
<h1 align="center">You're about to sign up for an Agilegram account</h1>
<br>
<br>
<br>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :firstname %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :firstname, class: "form-control", placeholder: "Enter first name", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :lastname %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :lastname, class: "form-control", placeholder: "Enter last name", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/users/show.html.erb
<h1 align="center"><%= @user.username %>'s feed</h1>
<div class="row">
 <div class="col-md-4 col-md-offset-5 center">
  <%= gravatar_for @user, size: 150 %>
 </div>
</div>
<h4 align="center"><%= @user.username %>'s posts</h4>
<%= render 'shared/post', obj: @user.posts %>
<div align="center">

</div>